[package]
name = "websocket-connect"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "*", features = ["native-tls"] }
tokio-stream = "0.1"
futures-util = "0.3"
url = "2.5"
